### ISSUE TITLE
Error message clipped

### ISSUE THREAD

**Issue by arvydaszenitech** [n4kz/react-native-material-textfield#18]
Hey, 
I found that error message under input filed will be clipped if text is too long. 
Could you please make it configurable to be able to show in multiline? 
<img width="228" alt="screenshot 2017-05-31 17 06 33" src="https://cloud.githubusercontent.com/assets/17194044/26635872/bd7f76a4-4623-11e7-8ba2-4744d77c86a4.png">

**Comment by n4kz** [comment]
Thanks for your feedback, it's slightly difficult to implement without loosing crossfade animation (requires absolute positioning). Will keep looking for suitable solution.

**Comment by jordanmkoncz** [comment]
@n4kz first of all just want to say thanks for your great work on this library.

I also ran into this issue with the error message and helper text being clipped to a single line. I think this is a big problem, as it's essential for a user to be able to read the full error message and helper text. There is no way a user of the app can properly fix a mistake in their input if they cannot actually see the full error message explaining what's wrong with their input.

With React Native app development we're catering to a huge variety of different devices with different screen sizes so even if you tried to ensure all your error messages and helper text were less than X characters long, there will still be devices that will result in some error messages and help text being cut off.

Something else to consider is that the current implementation does not adhere to the Material Design guidelines. The guidelines at https://material.io/guidelines/components/text-fields.html, under "Helper text", state "Helper text gives context about a field’s input, such as how the input will be used... Specs: On a single line if possible, or with text wrapping (if multiple lines)". So if the helper text cannot be displayed on a single line, it should still be displayed in full and should wrap to the next line(s). The guidelines say the same regarding error text.

I understand what you're saying about how this is difficult to implement as it conflicts with how some animations are implemented. I would like to suggest that the library is updated so that it supports multiline helper text and error text, and does not include any animations which conflict with supporting this. That way it supports this essential functionality, and then possible options for bringing back animations which work with multiline text could be considered and added if a solution is found. Right now, the library is putting form over function and causing a huge usability problem just for the sake of some animations.

**Comment by Billy-** [comment]
@n4kz Have you had any further thoughts on this issue? Are you still able to actively maintain this package?

Kind regards,

**Comment by n4kz** [comment]
Sorry for delayed fix. Finally released `0.14.0` with multiline messages.
