### ISSUE TITLE
Label overflows the Input 

### ISSUE THREAD

**Issue by MoeMamdouh** [n4kz/react-native-material-textfield#197]
Hi there,
Thank you for this helpful library.
I faced a small issue so i need to share it with you. 
When i clicked on the left of the input outside it, the input is focused.

![Screen Shot 2019-11-09 at 4 58 25 PM](https://user-images.githubusercontent.com/16561058/68530596-37e0de80-0312-11ea-8690-ce711d051630.png)

And if you have two inputs in the same row its will be unexpected behaviour of focusing, when you click on one input the other one will be focused.
So after debugging i found that the input label overflow out the input it self
so i simply fixed it by add this style to the `containerStyle` prop:

```
<TextField
 ...
 containerStyle={overflow: 'hidden'}
/>
```

**Comment by matias91** [comment]
This fixes the wrong focus issue, but sadly also cut off half of the label 😞 
The repo seems to be abandoned. Such a shame, because is a great component.

<img width="300" alt="Screen Shot 2020-08-09 at 15 22 25" src="https://user-images.githubusercontent.com/2778383/89739094-2882f300-da54-11ea-9f22-bb4cd2e8b623.png">
