### ISSUE TITLE
react-native-vector-icons support missed

### ISSUE THREAD

**Issue by hosembafer** [n4kz/react-native-material-textfield#28]

**Comment by n4kz** [comment]
Please, explain what did you mean by react-native-vector-icons support?

**Comment by hosembafer** [comment]
https://github.com/halilb/react-native-textinput-effects have realised what I mean.

Of course I can do it myself by creation my own component with Icon and TextField wrapped in View. But react-native-material-textfield not friendly for styling of that type, for example, I have changed the core code of react-native-material-textfield to set paddingLeft to Label component.

And sorry for English

**Comment by hosembafer** [comment]
Prop | Type | Description
-- | -- | --
iconClass | Object | The Icon component class you've imported from react-native-vector-icons.
iconName | String | Name of the icon that is passed to Icon component.
iconColor | String | Applied to the Icon component.
iconSize | Number | Applied to the Icon component.

Parameters like that will be look very nice :)

**Comment by n4kz** [comment]
Thanks for detailed explanation. `react-native-material-textfield` was designed with material guidelines in mind, so sometimes it is not easy to achieve some custom styling. I'm not sure that linking to `react-native-vector-icons` as dependency is the right way of doing things, due to additional  steps required for installation. However I see some other possibilities here:

* Implement signifier icon support, same way as `renderAccessory` is implemented (icon will be rendered on the left side of the field). Icon will be always visible.
* Adjust `propTypes` for affixes (icon will be rendered inside, depending on affix type) to accept `Text` nodes. Icon will hide when label goes down.

**Comment by hosembafer** [comment]
![input-with-icons](https://user-images.githubusercontent.com/5071289/28571127-7717138e-7152-11e7-940e-f28035c1c38b.png)

Of course, I can do it somehow, but with your suggested methods there is no way to make inputs like in photo above. I mean border in the bottom must start from Icon's left, but it's not possible if I get it correctly. It's ok for me right now, but it will be megacool to include that feature.

**Comment by n4kz** [comment]
Well, yes. Material design guidelines suggest that underline should be aligned with label. So as a compromise I can implement signifier icon support with further styling done in a fork.

**Comment by hosembafer** [comment]
Now we have change the design like this and it's ok for us.

![input-with-icons v2](https://user-images.githubusercontent.com/5071289/28661410-93097bb0-72c7-11e7-8e57-e9e81ac10a1c.png)

I just suggest the improvement without knowledge of material design guidelines. Maybe it's not a good idea to include icon support inside of the textfield, I don't know :)

Issue can be closed.

**Comment by n4kz** [comment]
Okay :)

**Comment by ssscassio** [comment]
@hosembafer Can you say how did  you make this? I'm trying to Wrapp Icon and Material-Textfield on a View with flexDirection: 'row' but simple the TextField disappears.

`
<View style={{flexDirection: 'row'}}>
     <Icon name="search" size={20} color="#000"/>
        <TextField
            {...props}
         />
</View>
`
Every time that i wrap the TextField with a flexDirection: 'row' it disappears
