### ISSUE TITLE
Error while updating property 'selectionColor' of view managed by: AndroidTextInput

### ISSUE THREAD

**Issue by lbayarkhuu** [n4kz/react-native-material-textfield#54]
Please help me :))

            <TextField
              tintColor='#A72822'
              selectionColor={tintColor}
              ref={this.first_nameRef}
              label='Нэр'
              value={first_name}
              onFocus={this.onFocus}
              onChangeText={ (first_name) => this.setState({ first_name }) }
              multiline={true}
              maxLength={30}
              error={errors.first_name}
              returnKeyType = {"next"}
              onSubmitEditing={(event) => {
                this['last_name'].focus();
              }}
            />

![alt SS](https://preview.ibb.co/jOFm0b/22140122_972443722895056_2013935141_o.png)

**Comment by LilyMGoh** [comment]
I'm running into the same problem. On React Native 0.46 and Expo SDK v19.0.0.

**Comment by lbayarkhuu** [comment]
My phone is HTC m9. Android v6.0.

**Comment by cosmocoder** [comment]
I am also facing the same issue on a detached Expo project with React Native 0.48 and Expo SDK 21. Any solution to this?

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. I've read all linked issues and can tell that issue is not related to `TextField` directly. Looks like this should be fixed explicitly in RN or implicitly by removing some styling from android resource files.

Sorry, but I'm not using Expo myself and can help no further with research. However, if some suitable fix will be found, I'll merge PR or implement a fix.

**Comment by LilyMGoh** [comment]
Remove ` selectionColor={tintColor}` on line 484 in `src/components/field/index.js` should fix it.

**Comment by n4kz** [comment]
I believe that by fixing something we should not break other things and this property was not added by accident.
