### ISSUE TITLE
How to SHOW the bottom line?

### ISSUE THREAD

**Issue by amberv0** [n4kz/react-native-material-textfield#57]
Hi! After the commit where you allowed not showing the bottom line I can't figure out how to actually SHOW it when the field is NOT disabled.
This kind of works, but messes things up when the field is disabled. 
```
inputContainerStyle={{
                        borderBottomColor: 'red',
                        borderBottomWidth: 1,
                    }}
```

Thank you!

**Comment by n4kz** [comment]
Thanks for question. Disabled and normal states are customised in different ways, due to lack of dotted underline support for single side of a view in RN. For disabled state you have to update overridden styles accordingly. For more details please take look at default styles for input container in source [code](https://github.com/n4kz/react-native-material-textfield/blob/master/src/components/field/index.js#L365).

**Comment by syedamirali14** [comment]
@amberv0 
i fixed it with disabledLineWidth={5} or lineWidth={0.5}
