### ISSUE TITLE
Multiline helper(title) text

### ISSUE THREAD

**Issue by amihusb** [n4kz/react-native-material-textfield#59]
Awesome work.

Is it possible to have a multiline helper text?

**Comment by simba4everyoung** [comment]
+1

**Comment by n4kz** [comment]
Thanks for question and PR. That's very complicated task related to #18. I've not implemented it since May 31, as I see no easy way of having multiline helpers and error message without loosing crossfade animation and affecting character counter layout. However I keep looking for a solution and will implement it as soon as it will be found.

Sorry for delayed reply. I'm closing this issue, as it's closely related to #18.
