### ISSUE TITLE
Could not able to apply style attributes for Animated.View default padding top is 32

### ISSUE THREAD

**Issue by Dineshchitta** [n4kz/react-native-material-textfield#7]
I Want to apply my styles to Animated.View for example Default padding top is 32.I want to apply my own padding and some other attributes

**Comment by n4kz** [comment]
For this moment complete customisation is very difficult due to large number of child components and states. The main goal of developing this component is full compliance with current material design guidelines, so I'm not planning to add additional styling properties (only dense text field support at some point). Probably the best way to apply custom styles is to create a fork.
